version: "2"
linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - nakedret
  disable:
    - lll
run:
  timeout: 5m
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
