<script lang="ts">
  import { appState } from '../../state/appState.svelte';
  import { Modal, Button, toast } from '@ohjanus/ui';

  const ddlSql = `-- DDL definition for dev_mh_asset.public.connection_credential
-- Generated by OhJanus Schema Introspector on 2026-10-03

CREATE TABLE public.connection_credential (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    "createdDate" timestamp without time zone NOT NULL DEFAULT now(),
    "lastUpdatedDate" timestamp without time zone,
    "createdBy" uuid NOT NULL,
    "connectionType" character varying(64) NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb,
    CONSTRAINT connection_credential_pkey PRIMARY KEY (id)
);

CREATE INDEX idx_connection_credential_created_by ON public.connection_credential USING btree ("createdBy");
CREATE INDEX idx_connection_credential_type ON public.connection_credential USING btree ("connectionType");
`;

  function close() {
    appState.ddlModalOpen = false;
  }

  function copyDdl() {
    navigator.clipboard.writeText(ddlSql);
    toast.success('DDL copied to clipboard');
  }
</script>

<Modal
  open={appState.ddlModalOpen}
  title="Table DDL: public.connection_credential"
  width="580px"
  onClose={close}
>
  <pre class="ddl-code code-text">{ddlSql}</pre>

  {#snippet footer()}
    <Button variant="secondary" onclick={close}>Close</Button>
    <Button variant="primary" onclick={copyDdl}>Copy DDL</Button>
  {/snippet}
</Modal>

<style>
  .ddl-code {
    background-color: var(--bg-canvas, #1E1F22);
    border: 1px solid var(--border-default);
    padding: 12px;
    border-radius: 4px;
    font-size: 11px;
    line-height: 18px;
    color: var(--text-primary, #DFE1E5);
    max-height: 360px;
    overflow-y: auto;
    font-family: var(--font-mono, 'JetBrains Mono', monospace);
    margin: 0;
  }
</style>
