<script lang="ts">
  import { appState } from '../../state/appState.svelte';

  const ddlSql = `-- DDL definition for dev_mh_asset.public.connection_credential
-- Generated by OhJanus Schema Introspector on 2026-10-03

CREATE TABLE public.connection_credential (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    "createdDate" timestamp without time zone NOT NULL DEFAULT now(),
    "lastUpdatedDate" timestamp without time zone,
    "createdBy" uuid NOT NULL,
    "connectionType" character varying(64) NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb,
    CONSTRAINT connection_credential_pkey PRIMARY KEY (id)
);

CREATE INDEX idx_connection_credential_created_by ON public.connection_credential USING btree ("createdBy");
CREATE INDEX idx_connection_credential_type ON public.connection_credential USING btree ("connectionType");
`;

  function close() {
    appState.ddlModalOpen = false;
  }
</script>

{#if appState.ddlModalOpen}
  <!-- svelte-ignore a11y_click_events_have_key_events -->
  <!-- svelte-ignore a11y_no_static_element_interactions -->
  <div class="jb-modal-backdrop" onclick={close}>
    <div class="jb-modal" style="width: 580px;" onclick={(e) => e.stopPropagation()}>
      <div class="jb-modal-header">
        <span>Table DDL: public.connection_credential</span>
        <button class="jb-icon-btn" onclick={close}>✕</button>
      </div>

      <div class="jb-modal-body">
        <pre class="ddl-code code-text">{ddlSql}</pre>
      </div>

      <div class="jb-modal-footer">
        <button class="jb-btn-secondary" onclick={close}>Close</button>
        <button
          class="jb-btn-primary"
          onclick={() => {
            navigator.clipboard.writeText(ddlSql);
            alert('DDL copied to clipboard');
          }}
        >
          Copy DDL
        </button>
      </div>
    </div>
  </div>
{/if}

<style>
  .ddl-code {
    background-color: #1E1F22;
    border: 1px solid var(--border-default);
    padding: 12px;
    border-radius: 4px;
    font-size: 11px;
    line-height: 18px;
    color: #DFE1E5;
    max-height: 360px;
    overflow-y: auto;
  }
</style>
